from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.index, name='home'),
    # path('userhome/', views.index, name='userhome'),
    # path('hospitalhome/', views.index, name='userhome'),
    path('logout/', views.logout_view, name='logout'),
    path('contact/', views.contact, name="contact"),
    path('hospitals/', views.hospitals, name='hospitals'),
    path('hospitals/<int:hospital_id>', views.hospital_detail, name='hospitals'),
    # path('<int:id>', views.hospitals, name='hospital'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('about.html', views.about, name="about"),
    # path('blog-sidebar.html', views.posts, name="blog"),
    # path('hizmetler.html', views.services, name="services"),
    path('login/', views.login_view, name="login"),
    path('register/', views.register, name='signup'),
    path('doctors/', views.getdoctors, name='doctors'),
    path('edit_profile/', views.profile_edit, name='edit_profile'),
    # path('hlogin/', views.hlogin, name='hlogin'),
    path('hregister/', views.hospital_register, name='hregister'),
    path('doctors/<int:doctor_id>', views.doctor_detail, name='doctor_detail'),
    path('doctors/<int:doctor_id>/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('view_doctors/', views.view_doctors, name='view_doctors'),
    path('view_doctors/delete/<int:doctor_id>/', views.doctor_delete, name='doctor_delete'),
    path('update_doctor/<int:doctor_id>', views.doctor_update, name='doctor_update'),
    path('view_appointments/', views.view_appointments, name='view_appointments'),
    path('view_appointments/change/<int:appointment_id>', views.appointment_done, name='appointment_done'),
    # path('deneme/', views.schedule_view, name='schedule_view'),
    path('appointment/', views.appointment, name='appointment'),
    path('appointments/cancel/<int:appointment_id>', views.appointment_cancel, name='appointment_cancel'),
    path('appointments/', views.user_appointments, name='appointments'),
    path('ajax/load_locations/', views.appointment_load_locations, name='ajax_load_locations'),
    path('ajax/load_hospitals/', views.appointment_load_hospitals, name='ajax_load_hospitals'),
    path('ajax/load_doctors/', views.appointment_load_doctors, name='ajax_load_doctors'),
    path('ajax/load_dates/', views.appointment_load_dates, name='ajax_load_dates'),
    path('ajax/load_times/', views.appointment_load_times, name='ajax_load_times'),
    # path('appointment_final/', views.appointment_final, name='appointment_final'),
    path('add_schedule/', views.add_schedule, name='add_schedule'),
    path('view_schedule/', views.view_schedule, name='view_schedule'),
    path('view_schedule/delete/<int:schedule_id>', views.delete_schedule, name='delete_schedule'),
]
