# Generated by Django 4.1.1 on 2022-12-28 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.RESTRICT, to='home.times'),
        ),
    ]
