# Generated by Django 4.1.1 on 2022-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
