# Generated by Django 4.1.1 on 2022-12-28 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_times_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('field', 'location', 'hospital', 'doctor', 'user', 'date', 'time', 'status')},
        ),
    ]
