# Generated by Django 4.1.1 on 2022-12-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
