# Generated by Django 4.1.1 on 2023-01-06 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='hospital',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='sent_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
