# Generated by Django 4.1.1 on 2023-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comment_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_interval',
            field=models.CharField(blank=True, choices=[('Tüm saatler', 'Tüm saatler'), ('30 Dakikada Bir', '30 Dakikada Bir'), ('Saatte Bir', 'Saatte Bir')], default=None, max_length=20),
        ),
    ]
