# Generated by Django 4.1.1 on 2023-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment_rating_schedule_shift_schedule_time_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.BooleanField(default=False),
        ),
    ]
