# Generated by Django 4.1.1 on 2023-01-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_schedule_shift_schedule_last_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='hospital',
        ),
    ]
