# Generated by Django 4.1.1 on 2023-01-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_rating_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
