# Generated by Django 4.1.1 on 2023-01-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleDate',
        ),
    ]
