# Generated by Django 4.1.1 on 2023-01-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_exampledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hospital',
        ),
    ]
