# Generated by Django 4.1.1 on 2023-01-09 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_comment_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_detail',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
