# Generated by Django 4.1.1 on 2023-01-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_comment_doctor_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('title', 'comment_detail')},
        ),
    ]
